Add Citus integration smoke test
This adds a very basic run-through of pganalyze on a Citus
workload. It uses the latest Citus image and modifies the default
pgbench schema we use in stock Postgres tests to use Citus distributed
tables. This ensures monitoring features like calculating distributed
table sizes on Citus are properly exercised.

diff --git a/integration_test/Makefile b/integration_test/Makefile
--- a/integration_test/Makefile
+++ b/integration_test/Makefile
@@ -13,9 +13,9 @@ docker_run_cmd = docker run --name pganalyze-collector-test \
   -d pganalyze-collector-test $(1)
 docker_run_cmd_postgres = $(call docker_run_cmd,postgres -c pg_stat_statements.track_utility=off)
 
-.PHONY: pg96 pg10 pg11 pg12 pg13 pg14 pg15 reload guided-setup installer
+.PHONY: pg96 pg10 pg11 pg12 pg13 pg14 pg15 citus reload guided-setup installer
 
-all: pg96 pg10 pg11 pg12 pg13 pg14 pg15 reload guided-setup installer
+all: pg96 pg10 pg11 pg12 pg13 pg14 pg15 citus reload guided-setup installer
 
 pg96:
 	docker build -f Dockerfile.test-pg96 $(DOCKER_BUILD_OPTS)
@@ -177,6 +177,30 @@ pg15:
 	fi
 	jq '.queryInformations[].normalizedQuery' pg15_2.json | sort --version-sort -f > pg15.out
 	diff -Naur pg15.expected pg15.out && echo 'success'
+
+citus:
+	docker build -f Dockerfile.test-citus $(DOCKER_BUILD_OPTS)
+	$(docker_run_cmd_postgres)
+	sleep 10
+	docker exec pganalyze-collector-test pgbench -U postgres postgres -i
+	docker exec pganalyze-collector-test psql -U postgres postgres < citus-pgbench-ddl.sql
+	docker exec pganalyze-collector-test pgbench -U postgres postgres
+	docker exec pganalyze-collector-test sh -c "DB_USERNAME=postgres PGA_API_KEY=dummy PGA_DISABLE_ACTIVITY=1 IGNORE_SCHEMA_REGEXP=pgbench_history pganalyze-collector --dry-run --force-state-update -v" > citus_1.json
+	docker exec pganalyze-collector-test pgbench -U postgres postgres
+	docker exec pganalyze-collector-test sh -c "DB_USERNAME=postgres PGA_API_KEY=dummy PGA_DISABLE_ACTIVITY=1 IGNORE_SCHEMA_REGEXP=pgbench_history pganalyze-collector --dry-run --force-state-update -v" > citus_2.json
+	docker rm -f pganalyze-collector-test
+	docker rmi pganalyze-collector-test
+	if [ "`jq '.collectorErrors' citus_2.json | tr -d ' \n\r\t '`" != "null" ]; then \
+		jq '.collectorErrors' citus_2.json; \
+		exit 1; \
+	fi
+	if jq '.relationReferences' citus_2.json | grep --quiet pgbench_history; then \
+                echo "failed to ignore table according to IGNORE_SCHEMA_REGEXP=pgbench_history" \
+		jq '.relationReferences' citus_2.json; \
+		exit 1; \
+	fi
+	jq '.queryInformations[].normalizedQuery' citus_2.json | sort --version-sort -f > citus.out
+	diff -Naur citus.expected citus.out && echo 'success'
 
 # Test reload both with an empty config and a server present
 #
