Add integration tests for Postgres 14 and 15

diff --git a/integration_test/Makefile b/integration_test/Makefile
--- a/integration_test/Makefile
+++ b/integration_test/Makefile
@@ -10,9 +10,9 @@ docker_run_cmd = docker run --name pganalyze-collector-test \
   -d pganalyze-collector-test $(1)
 docker_run_cmd_postgres = $(call docker_run_cmd,postgres -c pg_stat_statements.track_utility=off)
 
-.PHONY: pg93 pg94 pg95 pg96 pg10 pg11 pg12 pg13 reload guided-setup installer
+.PHONY: pg93 pg94 pg95 pg96 pg10 pg11 pg12 pg13 pg14 pg15 reload guided-setup installer
 
-all: pg93 pg94 pg95 pg96 pg10 pg11 pg12 pg13 reload guided-setup installer
+all: pg93 pg94 pg95 pg96 pg10 pg11 pg12 pg13 pg14 pg15 reload guided-setup installer
 
 pg93:
 	docker build -f Dockerfile.test-pg93 $(DOCKER_BUILD_OPTS)
@@ -197,6 +197,52 @@ pg13:
 	fi
 	jq '.queryInformations[].normalizedQuery' pg13_2.json | sort --version-sort -f > pg13.out
 	diff -Naur pg13.expected pg13.out && echo 'success'
+
+pg14:
+	docker build -f Dockerfile.test-pg14 $(DOCKER_BUILD_OPTS)
+	$(docker_run_cmd_postgres)
+	sleep 10
+	docker exec pganalyze-collector-test pgbench -U postgres postgres -i
+	docker exec pganalyze-collector-test pgbench -U postgres postgres
+	docker exec pganalyze-collector-test sh -c "DB_USERNAME=postgres PGA_API_KEY=dummy PGA_DISABLE_ACTIVITY=1 IGNORE_SCHEMA_REGEXP=pgbench_history pganalyze-collector --dry-run --force-state-update -v" > pg14_1.json
+	docker exec pganalyze-collector-test pgbench -U postgres postgres
+	docker exec pganalyze-collector-test sh -c "DB_USERNAME=postgres PGA_API_KEY=dummy PGA_DISABLE_ACTIVITY=1 IGNORE_SCHEMA_REGEXP=pgbench_history pganalyze-collector --dry-run --force-state-update -v" > pg14_2.json
+	docker rm -f pganalyze-collector-test
+	docker rmi pganalyze-collector-test
+	if [ "`jq '.collectorErrors' pg14_2.json | tr -d ' \n\r\t '`" != "null" ]; then \
+		jq '.collectorErrors' pg14_2.json; \
+		exit 1; \
+	fi
+	if jq '.relationReferences' pg14_2.json | grep --quiet pgbench_history; then \
+                echo "failed to ignore table according to IGNORE_SCHEMA_REGEXP=pgbench_history" \
+		jq '.relationReferences' pg14_2.json; \
+		exit 1; \
+	fi
+	jq '.queryInformations[].normalizedQuery' pg14_2.json | sort --version-sort -f > pg14.out
+	diff -Naur pg14.expected pg14.out && echo 'success'
+
+pg15:
+	docker build -f Dockerfile.test-pg15 $(DOCKER_BUILD_OPTS)
+	$(docker_run_cmd_postgres)
+	sleep 10
+	docker exec pganalyze-collector-test pgbench -U postgres postgres -i
+	docker exec pganalyze-collector-test pgbench -U postgres postgres
+	docker exec pganalyze-collector-test sh -c "DB_USERNAME=postgres PGA_API_KEY=dummy PGA_DISABLE_ACTIVITY=1 IGNORE_SCHEMA_REGEXP=pgbench_history pganalyze-collector --dry-run --force-state-update -v" > pg15_1.json
+	docker exec pganalyze-collector-test pgbench -U postgres postgres
+	docker exec pganalyze-collector-test sh -c "DB_USERNAME=postgres PGA_API_KEY=dummy PGA_DISABLE_ACTIVITY=1 IGNORE_SCHEMA_REGEXP=pgbench_history pganalyze-collector --dry-run --force-state-update -v" > pg15_2.json
+	docker rm -f pganalyze-collector-test
+	docker rmi pganalyze-collector-test
+	if [ "`jq '.collectorErrors' pg15_2.json | tr -d ' \n\r\t '`" != "null" ]; then \
+		jq '.collectorErrors' pg15_2.json; \
+		exit 1; \
+	fi
+	if jq '.relationReferences' pg15_2.json | grep --quiet pgbench_history; then \
+                echo "failed to ignore table according to IGNORE_SCHEMA_REGEXP=pgbench_history" \
+		jq '.relationReferences' pg15_2.json; \
+		exit 1; \
+	fi
+	jq '.queryInformations[].normalizedQuery' pg15_2.json | sort --version-sort -f > pg15.out
+	diff -Naur pg15.expected pg15.out && echo 'success'
 
 # Test reload both with an empty config and a server present
 #
