Add integration test for install script
Since the script operates on published packages, it cannot test the
actual packages that would be built based on the tested commit, but it
can run the script from the tested commit with the latest published
packages. Since the install script has few interactions with the
package contents (except for assumptions about the overall structure),
this is still useful in testing the install script itself.

diff --git a/integration_test/Makefile b/integration_test/Makefile
--- a/integration_test/Makefile
+++ b/integration_test/Makefile
@@ -10,9 +10,9 @@ DOCKER_RUN_CMD = docker run --name pganalyze-collector-test \
   -d \
   pganalyze-collector-test
 
-.PHONY: pg93 pg94 pg95 pg96 pg10 pg11 pg12 pg13 guided-setup
+.PHONY: pg93 pg94 pg95 pg96 pg10 pg11 pg12 pg13 guided-setup installer
 
-all: pg93 pg94 pg95 pg96 pg10 pg11 pg12 pg13 guided-setup
+all: pg93 pg94 pg95 pg96 pg10 pg11 pg12 pg13 guided-setup installer
 
 pg93:
 	docker build -f Dockerfile.test-pg93 $(DOCKER_BUILD_OPTS)
@@ -230,3 +230,18 @@ guided-setup:
 		exit 1; \
 	fi
 	diff -Nau guided-setup.snapshot-subset.json.expected guided-setup.snapshot-subset.json.out && echo 'success'
+
+installer:
+	docker build -f Dockerfile.test-guided-setup $(DOCKER_BUILD_OPTS)
+	$(DOCKER_RUN_CMD)
+	sleep 10
+
+	docker exec --privileged pganalyze-collector-test env PGA_INSTALL_NONINTERACTIVE=true PGA_API_KEY=abc123 bash -c '</collector/contrib/install.sh bash' >install.out
+	docker rm -f pganalyze-collector-test
+	docker rmi pganalyze-collector-test
+
+	if ! grep -q 'The pganalyze collector was installed successfully' install.out; then \
+		echo "expected installer to install latest published package; test failed:"; \
+		cat install.out; \
+		exit 1; \
+	fi
