Add integration test for Postgres 17 (#600)

diff --git a/integration_test/Makefile b/integration_test/Makefile
--- a/integration_test/Makefile
+++ b/integration_test/Makefile
@@ -185,6 +185,29 @@ pg16:
 	jq '.queryInformations[].normalizedQuery' pg16_2.json | sort --version-sort -f > pg16.out
 	diff -Naur pg16.expected pg16.out && echo 'success'
 
+pg17:
+	docker build -f Dockerfile.test-pg17 $(DOCKER_BUILD_OPTS)
+	$(docker_run_cmd_postgres)
+	sleep 10
+	docker exec pganalyze-collector-test pgbench -U postgres postgres -i
+	docker exec pganalyze-collector-test pgbench -U postgres postgres
+	docker exec pganalyze-collector-test sh -c "DB_USERNAME=postgres PGA_API_KEY=dummy PGA_DISABLE_ACTIVITY=1 IGNORE_SCHEMA_REGEXP=pgbench_history pganalyze-collector --dry-run --force-state-update -v" > pg17_1.json
+	docker exec pganalyze-collector-test pgbench -U postgres postgres
+	docker exec pganalyze-collector-test sh -c "DB_USERNAME=postgres PGA_API_KEY=dummy PGA_DISABLE_ACTIVITY=1 IGNORE_SCHEMA_REGEXP=pgbench_history pganalyze-collector --dry-run --force-state-update -v" > pg17_2.json
+	docker rm -f pganalyze-collector-test
+	docker rmi pganalyze-collector-test
+	if [ "`jq '.collectorErrors' pg17_2.json | tr -d ' \n\r\t '`" != "null" ]; then \
+		jq '.collectorErrors' pg17_2.json; \
+		exit 1; \
+	fi
+	if jq '.relationReferences' pg17_2.json | grep --quiet pgbench_history; then \
+                echo "failed to ignore table according to IGNORE_SCHEMA_REGEXP=pgbench_history" \
+		jq '.relationReferences' pg17_2.json; \
+		exit 1; \
+	fi
+	jq '.queryInformations[].normalizedQuery' pg17_2.json | sort --version-sort -f > pg17.out
+	diff -Naur pg17.expected pg17.out && echo 'success'
+
 citus:
 	docker build -f Dockerfile.test-citus $(DOCKER_BUILD_OPTS)
 	$(docker_run_cmd_postgres)
